#! /bin/bash
ping -c 3 110.242.68.66 > /dev/null 2>&1
if [ $? -ne 0 ];then
    wanip=`ifconfig wan | grep 'inet addr:' | grep -oE '([0-9]{1,3}.){3}.[0-9]{1,3}' | head -n 1`
    rm  -f /root/urllink.txt
    wget -N 1.1.1.1 -a urllink.txt
    date1=`echo -e "$(<urllink.txt)"`
    date2=${date1#*vlan=}
    date3=${date2%%&*}
curl $geturl  -d  $getlist -H "Content-Type: application/x-www-form-urlencoded" -H "User-Agent:Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36" -output
else
exit 0
fi 
